-- 50 новых видов птиц России и СНГ
INSERT INTO t_p98872536_quantum_discovery_4.bird_species (latin_name, russian_name, english_name, order_name, family_name, is_rare, is_protected) VALUES
('Passer domesticus',        'Домовый воробей',          'House Sparrow',            'Воробьинообразные', 'Воробьиные',      FALSE, FALSE),
('Corvus cornix',            'Серая ворона',             'Hooded Crow',              'Воробьинообразные', 'Врановые',        FALSE, FALSE),
('Corvus corax',             'Ворон',                    'Common Raven',             'Воробьинообразные', 'Врановые',        FALSE, FALSE),
('Pica pica',                'Сорока',                   'Eurasian Magpie',          'Воробьинообразные', 'Врановые',        FALSE, FALSE),
('Garrulus glandarius',      'Сойка',                    'Eurasian Jay',             'Воробьинообразные', 'Врановые',        FALSE, FALSE),
('Sturnus vulgaris',         'Обыкновенный скворец',     'Common Starling',          'Воробьинообразные', 'Скворцовые',      FALSE, FALSE),
('Fringilla coelebs',        'Зяблик',                   'Common Chaffinch',         'Воробьинообразные', 'Вьюрковые',       FALSE, FALSE),
('Erithacus rubecula',       'Зарянка',                  'European Robin',           'Воробьинообразные', 'Мухоловковые',    FALSE, FALSE),
('Sylvia communis',          'Серая славка',             'Common Whitethroat',       'Воробьинообразные', 'Камышевковые',    FALSE, FALSE),
('Phylloscopus trochilus',   'Весничка',                 'Willow Warbler',           'Воробьинообразные', 'Пеночковые',      FALSE, FALSE),
('Motacilla alba',           'Белая трясогузка',         'White Wagtail',            'Воробьинообразные', 'Трясогузковые',   FALSE, FALSE),
('Motacilla flava',          'Жёлтая трясогузка',       'Western Yellow Wagtail',   'Воробьинообразные', 'Трясогузковые',   FALSE, FALSE),
('Anthus pratensis',         'Луговой конёк',            'Meadow Pipit',             'Воробьинообразные', 'Трясогузковые',   FALSE, FALSE),
('Upupa epops',              'Удод',                     'Eurasian Hoopoe',          'Удодообразные',     'Удодовые',        FALSE, FALSE),
('Cuculus canorus',          'Обыкновенная кукушка',     'Common Cuckoo',            'Кукушкообразные',   'Кукушковые',      FALSE, FALSE),
('Streptopelia decaocto',    'Кольчатая горлица',        'Eurasian Collared Dove',   'Голубеобразные',    'Голубиные',       FALSE, FALSE),
('Columba livia',            'Сизый голубь',             'Rock Dove',                'Голубеобразные',    'Голубиные',       FALSE, FALSE),
('Apus apus',                'Чёрный стриж',             'Common Swift',             'Стрижеобразные',    'Стрижиные',       FALSE, FALSE),
('Alcedo atthis',            'Обыкновенный зимородок',   'Common Kingfisher',        'Ракшеобразные',     'Зимородковые',    FALSE, TRUE),
('Picus viridis',            'Зелёный дятел',            'European Green Woodpecker','Дятлообразные',     'Дятловые',        FALSE, FALSE),
('Dendrocopos major',        'Большой пёстрый дятел',   'Great Spotted Woodpecker', 'Дятлообразные',     'Дятловые',        FALSE, FALSE),
('Dryocopus martius',        'Чёрный дятел',             'Black Woodpecker',         'Дятлообразные',     'Дятловые',        FALSE, FALSE),
('Accipiter nisus',          'Перепелятник',             'Eurasian Sparrowhawk',     'Ястребообразные',   'Ястребиные',      FALSE, FALSE),
('Accipiter gentilis',       'Тетеревятник',             'Northern Goshawk',         'Ястребообразные',   'Ястребиные',      FALSE, FALSE),
('Buteo buteo',              'Обыкновенный канюк',       'Common Buzzard',           'Ястребообразные',   'Ястребиные',      FALSE, FALSE),
('Milvus migrans',           'Чёрный коршун',            'Black Kite',               'Ястребообразные',   'Ястребиные',      FALSE, FALSE),
('Circus aeruginosus',       'Болотный лунь',            'Western Marsh Harrier',    'Ястребообразные',   'Ястребиные',      FALSE, FALSE),
('Circus cyaneus',           'Полевой лунь',             'Hen Harrier',              'Ястребообразные',   'Ястребиные',      FALSE, FALSE),
('Falco tinnunculus',        'Обыкновенная пустельга',   'Common Kestrel',           'Соколообразные',    'Соколиные',       FALSE, FALSE),
('Falco subbuteo',           'Чеглок',                   'Eurasian Hobby',           'Соколообразные',    'Соколиные',       FALSE, FALSE),
('Falco columbarius',        'Дербник',                  'Merlin',                   'Соколообразные',    'Соколиные',       FALSE, FALSE),
('Falco cherrug',            'Балобан',                  'Saker Falcon',             'Соколообразные',    'Соколиные',       TRUE,  TRUE),
('Bubo bubo',                'Филин',                    'Eurasian Eagle-Owl',       'Совообразные',      'Совиные',         FALSE, TRUE),
('Strix aluco',              'Неясыть серая',            'Tawny Owl',                'Совообразные',      'Совиные',         FALSE, FALSE),
('Asio otus',                'Ушастая сова',             'Long-eared Owl',           'Совообразные',      'Совиные',         FALSE, FALSE),
('Asio flammeus',            'Болотная сова',            'Short-eared Owl',          'Совообразные',      'Совиные',         FALSE, FALSE),
('Tetrao urogallus',         'Глухарь',                  'Western Capercaillie',     'Курообразные',      'Тетеревиные',     FALSE, FALSE),
('Lyrurus tetrix',           'Тетерев',                  'Black Grouse',             'Курообразные',      'Тетеревиные',     FALSE, FALSE),
('Lagopus lagopus',          'Белая куропатка',          'Willow Ptarmigan',         'Курообразные',      'Тетеревиные',     FALSE, FALSE),
('Perdix perdix',            'Серая куропатка',          'Grey Partridge',           'Курообразные',      'Фазановые',       FALSE, FALSE),
('Coturnix coturnix',        'Перепел',                  'Common Quail',             'Курообразные',      'Фазановые',       FALSE, FALSE),
('Vanellus vanellus',        'Чибис',                    'Northern Lapwing',         'Ржанкообразные',    'Ржанковые',       FALSE, FALSE),
('Pluvialis apricaria',      'Золотистая ржанка',        'European Golden Plover',   'Ржанкообразные',    'Ржанковые',       FALSE, FALSE),
('Calidris alpina',          'Чернозобик',               'Dunlin',                   'Ржанкообразные',    'Бекасовые',       FALSE, FALSE),
('Gallinago gallinago',      'Бекас',                    'Common Snipe',             'Ржанкообразные',    'Бекасовые',       FALSE, FALSE),
('Numenius arquata',         'Большой кроншнеп',         'Eurasian Curlew',          'Ржанкообразные',    'Бекасовые',       TRUE,  TRUE),
('Larus argentatus',         'Серебристая чайка',        'European Herring Gull',    'Ржанкообразные',    'Чайковые',        FALSE, FALSE),
('Larus ridibundus',         'Озёрная чайка',           'Black-headed Gull',        'Ржанкообразные',    'Чайковые',        FALSE, FALSE),
('Sterna hirundo',           'Речная крачка',            'Common Tern',              'Ржанкообразные',    'Чайковые',        FALSE, FALSE),
('Phalacrocorax carbo',      'Большой баклан',           'Great Cormorant',          'Пеликанообразные',  'Баклановые',      FALSE, FALSE);
